- name: Add ambassador's chart repository to Helm
  community.kubernetes.helm_repository:
    name: datawire
    repo_url: "https://www.getambassador.io"
  when: ingress_provider == 'ambassador'

- name: Create ambassador ingress controller
  community.kubernetes.helm:
    name: "{{ ingress_name }}"
    chart_ref: datawire/ambassador
    release_namespace: "{{ ingress_namespace }}"
  when: ingress_provider == 'ambassador'

- name: Add nginx's chart repository to Helm
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
  when: ingress_provider == 'nginx'

- name: Create nginx ingress controller
  community.kubernetes.helm:
    name: "{{ ingress_name }}"
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: "{{ ingress_namespace }}"
  when: ingress_provider == 'nginx'

- name: Add traefik's chart repository to Helm
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: "https://containous.github.io/traefik-helm-chart"
  when: ingress_provider == 'traefik'

- name: Create traefik ingress controller
  community.kubernetes.helm:
    name: "{{ ingress_name }}"
    chart_ref: traefik/traefik
    release_namespace: "{{ ingress_namespace }}"
  when: ingress_provider == 'traefik'

- name: Add voyager's chart repository to Helm
  community.kubernetes.helm_repository:
    name: appscode
    repo_url: "https://charts.appscode.com/stable/"
  when: ingress_provider == 'voyager'

- name: Create voyager ingress controller
  community.kubernetes.helm:
    name: "{{ ingress_name }}"
    chart_ref: appscode/voyager
    release_namespace: "{{ ingress_namespace }}"
  when: ingress_provider == 'voyager'